sudo: false
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - python3-pip
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - mkdir -p $PWD/ninja
  - curl -L https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip -o $PWD/ninja/ninja-linux.zip
  - unzip $PWD/ninja/ninja-linux.zip -d $PWD/ninja
  - pip3 install --user meson
  - export PATH=$PATH:$PWD/ninja:~/.local

script: ./configure && make && make test
