sudo: required
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - python3-pip
      env:
        - CC=gcc-7

install:
  - mkdir -p $PWD/ninja
  - curl -L https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip -o $PWD/ninja/ninja-linux.zip
  - unzip $PWD/ninja/ninja-linux.zip -d $PWD/ninja
  - pip3 install --user meson
  - export PATH=$PATH:$PWD/ninja:~/.local

script: ./configure && make && make test
